import type { AssetRecord } from "@/lib/schemas";

/** Shared sample assets — used by demo mode and mock xlsx generator. */
export const SAMPLE_ASSETS: AssetRecord[] = [
  {
    floorId: "01",
    facilityName: "Riverside Medical Center",
    facilityType: "Healthcare",
    facilityLevel: "Basement",
    roomNumber: "B-101",
    roomName: "Mechanical Room",
    areaServed: "ICU Wing / OR Suite",
    cmmsId: "AHU-001",
    assetName: "AHU-1",
    manufacturer: "Carrier",
    modelNumber: "39MBB030",
    serialNumber: "2918KA07263",
    installYear: 2008,
    notes: "Minor corrosion on drain pan. Filter housing bent.",
    fcaScore: 3,
    assetType: "Air Handling Unit",
    assetSize: "30 Ton",
    quantityMultiplier: 1,
    uom: "EA",
    repairOrReplace: "Repair",
    observedLifeRemaining: 4,
    observedReplacementYear: 2030,
    unitProbableCost: 18000,
    facilitySqft: 85000,
    assessmentDate: "2026-06-25",
    operationalImpact: 5,
    energyImpact: 5,
  },
  {
    floorId: "01",
    facilityName: "Riverside Medical Center",
    facilityType: "Healthcare",
    facilityLevel: "Roof Level",
    roomNumber: "R-01",
    roomName: "Rooftop Mechanical",
    areaServed: "Admin Wing",
    cmmsId: "RTU-002",
    assetName: "RTU-2",
    manufacturer: "Lennox",
    modelNumber: "LGH240H4BM1G",
    serialNumber: "5820H24568",
    installYear: 2015,
    notes: "Economizer damper seized. Refrigerant charge OK.",
    fcaScore: 2,
    assetType: "Packaged Rooftop Unit",
    assetSize: "20 Ton",
    quantityMultiplier: 1,
    uom: "EA",
    repairOrReplace: "Repair",
    observedLifeRemaining: 2,
    observedReplacementYear: 2028,
    unitProbableCost: 22000,
    facilitySqft: 85000,
    assessmentDate: "2026-06-25",
    operationalImpact: 4,
    energyImpact: 5,
  },
  {
    floorId: "01",
    facilityName: "Riverside Medical Center",
    facilityType: "Healthcare",
    facilityLevel: "Basement",
    roomNumber: "B-102",
    roomName: "Boiler Room",
    areaServed: "Perimeter Radiation / Domestic HW",
    cmmsId: "BLRP-001",
    assetName: "BLR-1",
    manufacturer: "Cleaver-Brooks",
    modelNumber: "ClearFire-C CF-200",
    serialNumber: "CB-20213847",
    installYear: 2012,
    notes: "Annual service completed. Burner assembly cleaned.",
    fcaScore: 4,
    assetType: "Boiler",
    assetSize: "200 BHP",
    quantityMultiplier: 2,
    uom: "EA",
    repairOrReplace: "Maintain",
    observedLifeRemaining: 11,
    observedReplacementYear: 2037,
    unitProbableCost: 48000,
    facilitySqft: 85000,
    assessmentDate: "2026-06-25",
    operationalImpact: 5,
    energyImpact: 4,
  },
  {
    floorId: "02",
    facilityName: "Riverside Medical Center",
    facilityType: "Healthcare",
    facilityLevel: "2nd Floor",
    roomNumber: "E-201",
    roomName: "Electrical Room",
    areaServed: "Full Building",
    cmmsId: "XFMR-001",
    assetName: "XFMR-1",
    manufacturer: "Square D",
    modelNumber: "EX75T3HCU",
    serialNumber: "9827A44821",
    installYear: 2005,
    notes: "Discoloration on secondary terminals. NETA test recommended.",
    fcaScore: 2,
    assetType: "Dry Type Transformer",
    assetSize: "75 kVA / 480-208Y/120V",
    quantityMultiplier: 1,
    uom: "EA",
    repairOrReplace: "Replace",
    observedLifeRemaining: 1,
    observedReplacementYear: 2027,
    unitProbableCost: 20000,
    facilitySqft: 85000,
    assessmentDate: "2026-06-25",
    operationalImpact: 5,
    energyImpact: 1,
  },
  {
    floorId: "02",
    facilityName: "Riverside Medical Center",
    facilityType: "Healthcare",
    facilityLevel: "2nd Floor",
    roomNumber: "E-201",
    roomName: "Electrical Room",
    areaServed: "Critical Life Safety Circuit",
    cmmsId: "GENSET-001",
    assetName: "GENSET-1",
    manufacturer: "Cummins",
    modelNumber: "C500D6R",
    serialNumber: "J-100012245",
    installYear: 2018,
    notes: "Load bank test 2025-11. Transfer time within spec.",
    fcaScore: 5,
    assetType: "Emergency Generator",
    assetSize: "500 kW / 480V",
    quantityMultiplier: 1,
    uom: "EA",
    repairOrReplace: "Maintain",
    observedLifeRemaining: 17,
    observedReplacementYear: 2043,
    unitProbableCost: 60000,
    facilitySqft: 85000,
    assessmentDate: "2026-06-25",
    operationalImpact: 5,
    energyImpact: 2,
  },
  {
    floorId: "01",
    facilityName: "Riverside Medical Center",
    facilityType: "Healthcare",
    facilityLevel: "Basement",
    roomNumber: "B-105",
    roomName: "Domestic Water Room",
    areaServed: "Building-Wide DHW",
    cmmsId: "WH-001",
    assetName: "WH-1",
    manufacturer: "A.O. Smith",
    modelNumber: "BTXL-120-ASME",
    serialNumber: "AOS-190874621",
    installYear: 2017,
    notes: "Sacrificial anode condition unknown. Schedule service.",
    fcaScore: 3,
    assetType: "Commercial Water Heater",
    assetSize: "120 Gal / 300 MBH",
    quantityMultiplier: 3,
    uom: "EA",
    repairOrReplace: "Maintain",
    observedLifeRemaining: 6,
    observedReplacementYear: 2032,
    unitProbableCost: 9500,
    facilitySqft: 85000,
    assessmentDate: "2026-06-25",
    operationalImpact: 4,
    energyImpact: 2,
  },
  {
    floorId: "01",
    facilityName: "Riverside Medical Center",
    facilityType: "Healthcare",
    facilityLevel: "Basement",
    roomNumber: "B-110",
    roomName: "Fire Pump Room",
    areaServed: "Sprinkler System – Full Building",
    cmmsId: "FP-001",
    assetName: "FP-1",
    manufacturer: "Peerless",
    modelNumber: "AE4AE-20",
    serialNumber: "PRL-20172271",
    installYear: 2010,
    notes: "Annual fire pump test passed. Packing gland drips slightly.",
    fcaScore: 4,
    assetType: "Fire Pump",
    assetSize: "750 GPM @ 100 PSI",
    quantityMultiplier: 1,
    uom: "EA",
    repairOrReplace: "Maintain",
    observedLifeRemaining: 4,
    observedReplacementYear: 2030,
    unitProbableCost: 20000,
    facilitySqft: 85000,
    assessmentDate: "2026-06-25",
    operationalImpact: 5,
    energyImpact: 1,
  },
  {
    floorId: "01",
    facilityName: "Riverside Medical Center",
    facilityType: "Healthcare",
    facilityLevel: "1st Floor",
    roomNumber: "112",
    roomName: "Fire Command Center",
    areaServed: "Campus-Wide Life Safety",
    cmmsId: "FACP-001",
    assetName: "FACP-1",
    manufacturer: "Notifier",
    modelNumber: "NFS2-3030",
    serialNumber: "NTF-20091188",
    installYear: 2009,
    notes: "Firmware out of support. Six zone cards showing supervisory fault.",
    fcaScore: 2,
    assetType: "Fire Alarm Control Panel",
    assetSize: "3030 Points",
    quantityMultiplier: 1,
    uom: "EA",
    repairOrReplace: "Replace",
    observedLifeRemaining: 0,
    observedReplacementYear: 2026,
    unitProbableCost: 14000,
    facilitySqft: 85000,
    assessmentDate: "2026-06-25",
    operationalImpact: 5,
    energyImpact: 1,
  },
];
